---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

Here, we're just setting a few options.

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```

```{r prepare_codebook}
library(tidyverse)
library(codebook)
library(haven)
library(labelled)

rr_human_data_with_reversed_items = rio::import("../synth-rep-dataset/data/processed/sosci_labelled.rds")
reversed_items <- str_sub(names(rr_human_data_with_reversed_items)[str_detect(names(rr_human_data_with_reversed_items), "_R$")], 1, -3)
rr_human_data_with_inclusion_criteria = rio::import("../synth-rep-dataset/data/processed/sosci_labelled_with_exclusion_criteria.rds")
# setdiff(names(rr_human_data_with_inclusion_criteria), names(rr_human_data_with_reversed_items)) %>% dput()
rr_human_data_with_inclusion_criteria <- rr_human_data_with_inclusion_criteria %>% select(one_of(c("CASE","even_odd", "psychant", 
"psychsyn", "mahal_dist", 
"longstring", "time_per_item", "included")))
rr_human_data_with_inclusion_criteria <- rr_human_data_with_inclusion_criteria %>% 
  full_join(rr_human_data_with_reversed_items)
rr_human_data_included <- rr_human_data_with_inclusion_criteria %>% filter(included) %>% 
  select(-starts_with("BH"), -starts_with("SD"), -starts_with("WS"), -starts_with("BFI"),
         -QUESTNNR, -MODE, -one_of(reversed_items), -IFI_01, -ACH_01, -ACH_02, 
         -IFI_02, -FRI_02, -starts_with("MS"), -matches("^OC[0-9]"), -starts_with("PR"),
         -starts_with("RG"), -starts_with("ZY"))
```


```{r codebook}
codebook(rr_human_data_included)
```
